name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: "Build ${{ matrix.platform }}"
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-20.04, ubuntu-22.04, macos-latest, aarch64-linux]  # Add aarch64-linux
    env:
      PARALLEL: -j 2

    runs-on: "${{ matrix.platform }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache glslang / SPIRV-Tools
        id: cache-externals
        uses: actions/cache@v3
        with:
          path: external/*-build/output
          key: ${{ matrix.platform }} externals ${{ hashFiles('checkout_glslang_spirv_tools.sh', 'build_glslang_spirv_tools.sh') }}

      - name: Pull glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./checkout_glslang_spirv_tools.sh

      - name: Build glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./build_glslang_spirv_tools.sh Release 4

      - name: Configure SPIRV-Cross for aarch64
        shell: bash
        run: |
          mkdir build
          cd build
          # Here we are assuming the use of an appropriate cross-compilation toolchain
          # You might need to set up a cross-compilation toolchain file if needed for aarch64
          cmake .. -DSPIRV_CROSS_WERROR=ON -DSPIRV_CROSS_MISC_WARNINGS=ON -DSPIRV_CROSS_SHARED=ON -DCMAKE_INSTALL_PREFIX=output -DCMAKE_BUILD_TYPE=Release -DSPIRV_CROSS_ENABLE_TESTS=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ 

      - name: Build SPIRV-Cross
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --config Release --parallel 4
          cmake --build . --config Release --target install

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-binaries
          path: build/output
      - name: Test SPIRV-Cross
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C Release

  build-mobile:
    needs: build
    name: "Build ${{ matrix.sdk }}"
    strategy:
      matrix:
        include:
          - platform: iOS
            sdk: iphoneos
            architectures: arm64
          - platform: iOS
            sdk: iphonesimulator
            architectures: x86_64;arm64
          - platform: tvOS
            sdk: appletvos
            architectures: arm64
          - platform: tvOS
            sdk: appletvsimulator
            architectures: x86_64;arm64
          - platform: aarch64-linux  # Add ARM64 Linux for mobile platforms
            sdk: linux
            architectures: aarch64
    env:
      PARALLEL: -j 2

    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache glslang / SPIRV-Tools
        id: cache-externals
        uses: actions/cache@v3
        with:
          path: external/*-build/output
          key: ${{ matrix.platform }} externals ${{ hashFiles('checkout_glslang_spirv_tools.sh', 'build_glslang_spirv_tools.sh') }}

      - name: Pull glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./checkout_glslang_spirv_tools.sh

      - name: Build glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./build_glslang_spirv_tools.sh Release 4

      - name: Configure SPIRV-Cross for aarch64-linux
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DSPIRV_CROSS_WERROR=ON -DSPIRV_CROSS_MISC_WARNINGS=ON -DSPIRV_CROSS_SHARED=ON -DCMAKE_INSTALL_PREFIX=output -DCMAKE_BUILD_TYPE=Release -DSPIRV_CROSS_ENABLE_TESTS=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64

      - name: Build SPIRV-Cross
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --config Release --parallel 4
          cmake --build . --config Release --target install

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.sdk }}-binaries
          path: build/output

  reuse:
    name: "REUSE license check"
    runs-on: ubuntu-latest
    container: khronosgroup/docker-images:asciidoctor-spec

    steps:
      - uses: actions/checkout@v3

      # REUSE license checker
      - name: license-check
        run: |
          reuse lint
